config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  get 'home/about'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /books or /books.json
  def index
    @books = Book.where(["user_id = :u", { u: current_user.id }])
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    
    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    @book.user_id = current_user.id
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
      if @book.user_id != current_user.id
        redirect_to books_path, notice: "Not Authorized"
      end
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:book_name, :author)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end

  def about

  end  

end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
        #   redirect_to navigation_location
        redirect_to "/"
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Book name:</strong>
    <%= book.book_name %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p>

</div>

app/views/books/_bookrow.html.erb
<tr id="<%= dom_id book %>">
<td>
    <%= book.book_name %>
</td>
<td>
    <%= book.author %>
</td>
<td>
  <%= link_to "View", book,class:"btn btn-primary" %> | 
  <%= link_to "Edit", edit_book_path(book),class:"btn btn-warning" %> |
  <%= button_to "Destroy", book,method: :delete,class:"d-flex btn btn-danger",form: {style: 'display:inline-block;',data: { turbo_confirm: "Are you sure?" } } %>
</td>
</td>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:
      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      </div>
      <h2></h2>
    </div>
  <% end %>
  <div style="max-width:400px;padding:20px;border:solid black">

    <%= form.text_field :book_name, required: true,class:"form-control",placeholder: :book_name %>
    <br/>
    <%= form.text_field :author, required: true,class:"form-control",placeholder: :author  %>
    <br/>

    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back", books_path,class:"btn btn-secondary" %> | 
  <%= link_to "View", @book,class:"btn btn-primary" %>
</div>

app/views/books/index.html.erb
<% if @books.size > 0%>
<h1>Books</h1>

<table id="books" style="background-color:#fff;border:solid;border-spacing:2px" class="table table-striped table-light table-hover table-bordered">
<thead class="table-dark">
<tr>
<th>
Book name
</th>
<th>
Author
</th>
<th>
</th>
</tr>
</thead>
  <% @books.each do |book| %>
    <%= render 'bookrow', book:book %>
  <% end %>
</table>
<% else %>
<h1>You have no Books yet</h1>

<% end %>
<%= link_to "Add new book", new_book_path,class:"btn btn-secondary" %>

app/views/books/new.html.erb
<h1>Add New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back", books_path,class:"btn btn-secondary" %>
</div>

app/views/books/show.html.erb
<%= render @book %>

<div>
  <%= link_to "Back", books_path,class:"btn btn-secondary" %> |
  <%= link_to "Edit", edit_book_path(@book),class:"btn btn-warning" %> |
  <%= button_to "Destroy", @book, method: :delete,class:"btn btn-danger",form: {style: 'display:inline-block;',data: { turbo_confirm: "Are you sure?" } }%>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'I\'mOnRails', root_path,class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Books', books_path,class:"nav-link" %>
        </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'About', home_about_path,class:"nav-link" %>
        </li>
      </ul>
      
  <div class="d-flex navbar-nav">
  <% if user_signed_in? %>
    <ul class="navbar-nav" style="direction:rtl">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/fox.jpg" width="40" height="40" class="rounded-circle">
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'Edit Profile', edit_user_registration_path,class:"dropdown-item" %>
            <%= button_to 'Log Out', destroy_user_session_path,method: :delete,class:"dropdown-item" %>
        </div>
      </li>   
    </ul>
  <% else %>
    <%= link_to 'Sign In', new_user_session_path,class:"nav-link" %>
    <%= link_to 'Sign up', new_user_registration_path,class:"nav-link" %>
  <% end %>

  </div>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About</h1>

app/views/home/index.html.erb
<h1>Hello World!</h1>
<h3>This is a test project</h3>
<h5>Made by Abdalrahman S. Valabji</h5>
<h7>Enjoy!</h7>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imonrails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous"> %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body style="padding:3px">
  <%# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script> %>

    <%= render 'home/header' %>
  <div class="container">
      <% flash.each do |type, msg| %>
      <br/>
        <% if type == "notice" %>
          <div class="d-flex alert alert-primary alert-dismissible fade show" role="alert">
        <% else %>
          <div class="d-flex alert alert-danger alert-dismissible fade show" role="alert">
        <% end %>
          <%# <strong><%= type ></strong> %>
          <span style="flex:1" ><%= msg %></span>
          <button type="button" class="btn close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
      <% end %>
      
      <br/>
      <%# <p class="notice"><%= notice ></p>
      <p class="alert"><%= alert ></p> %>
    <%= yield %>
  </div>
  
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

  </body>
</html>